### ISSUE TITLE
[Bug]: Configuration can't be cached

### ISSUE THREAD

**Issue by creode-dev** [creode-modules/laravel-nova-assets#23]
### What happened?

I cannot cache the configuration due to how dynamic the values of the config are.

### How to reproduce the bug

Try and publish the config with default options, then try to run `php artisan config:cache`

### Package Version

2.0.0

### PHP Version

8.2.0

### Laravel Version

10.0.0

### Which operating systems does with happen with?

macOS

**Comment by jaymeh** [comment]
Fixed as part of latest version (2.4.1).
